config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'profile', to: 'users#show'
  end

  root to: 'pages#home'

  get "/play", to: "pages#play", as: :play

  get "moments/success/:friend_id", to: "moments#success", as: :moment_success

  put "/seen", to: "moments#seen", as: :seen

  get "moments/none", to: "moments#none", as: :moment_none

  # commented out friends / token related code to test moments uploads

  resources :moments, except: [:new] do
  get "/carrousel", to: "moments#carrousel"
end
get "moments/new/:token", to: "moments#new", as: :new_moment do

end


  resources :friends

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  after_save :send_friend_email
  acts_as_token_authenticatable
  belongs_to :user

  private

  def send_friend_email
    FriendMailer.with(friend: self).new_friend_email.deliver_now
  end
end

app/models/moment.rb
class Moment < ApplicationRecord

  mount_uploader :media, PhotoUploader
  belongs_to :user
  after_create_commit :assign_type

  VIDEO_TYPES = %w(mp4 mov avi wmv mkv flv 3gp).freeze
  IMG_TYPES = %w(jpg png jpeg gif bmp tiff pdf).freeze
  AUDIO_TYPES = %w(mp3 flac wav ogg).freeze

  private

  def assign_type
      self.update(media_type: self.media.resource_type)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :avatar, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :moments
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.all
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def new
    @friend = Friend.new
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
    if @friend.update(friend_params)
      redirect_to friends_path
    else
      render :edit
    end
  end

  def create
    @friend = Friend.new(friend_params)
    #token exists
    # how does the mailer make a mail
    @friend.user_id = current_user.id

    if @friend.save
      redirect_to friends_path

    else
      render :new
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy
    redirect_to friends_path
  end

  private

  def friend_params
    params.require(:friend).permit(:email, :phone_number, :name, :token)
  end
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
   skip_before_action :authenticate_user!, only: [:new, :create]

   def index
    if params[:query].present?

      if @friend = Friend.find_by("name ILIKE ?", "%#{params[:query]}%")
        @moments = Moment.where(friend_id: @friend.id)
        @videos = Moment.where(seen: true, friend_id: @friend.id, media_type: "video")
        @images = Moment.where(seen: true, friend_id: @friend.id, media_type: "image")
        @texts = Moment.where(friend_id: @friend.id, media: nil)
      else
        redirect_to moments_path
      end
    else
      @moments = Moment.where(seen: true).order(created_at: :asc)
      @videos = Moment.where(seen: true, media_type: "video")
      @images = Moment.where(seen: true, media_type: "image")
      @texts = Moment.where(media: nil)

  end
end

  def new
    token = params[:token]
    @friend = Friend.find_by(authentication_token: token)
    @moment = Moment.new
  end

  def create
    @moment = Moment.new(moments_params)

    if @moment.save
      # redirect to? Custom page after drag and drop
      redirect_to moment_success_path(friend_id: moments_params[:friend_id])
    else
      render :new
    end
  end

  def seen
    moment_ids = params[:moment_ids]
    moment_ids.split(',').each do |id|
      moment = Moment.find(id)
      moment.update(seen: true)
    end

    redirect_to moments_path

  end

  def success
    @friend = Friend.find(params[:friend_id])
  end

  def show
    @moments = Moment.where(user: current_user)
    @unseen_moments = @moments.select { |moment| !moment.seen }

    if @unseen_moments.empty?
      redirect_to moment_none_path
      # Redirect to timeline or special page: You've played all your moments of the day!'
    else
      @moments = @unseen_moments.first(5)
    end
  end

  def carrousel
    user = User.find(1)
    @current_user = current_user
    @moments = Moment.where(seen: true, user: user)
    @moment = Moment.find(params[:moment_id])
  end

  def tagging
    # tag method here. Need to update schema to add a tag field to moments.
  end

  def destroy
    moment = Moment.find(params[:id])
    moment.destroy
    # redirect_to timeline page?
  end

  private

  def moments_params
    params.require(:moment).permit(:text_content, :media, :user_id, :friend_id, :seen)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @unseens = Moment.where(seen: false).where.not(media: nil)
  end

  def play
    @moments = Moment.where(seen: false).where.not(media: nil).sample(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_friend_edit.html.erb
<div class="edit-form">
  <%= simple_form_for (friend) do |f| %>
    <%= f.error_notification %>
      <div class="inputs-div">
        <%= f.input :name, :label => false %>
        <%= f.input :email, :label => false, input_html: { autocomplete: 'email' } %>
      </div>
  <%#= f.input :avatar, as: :file, input_html: { accept: User::AVATAR } %>
      <div class="submit-cancel-buttons">
        <div>
          <%= button_tag type: 'submit' do %>
            <%= image_tag "accept.png" %>
          <% end %>
          <%= button_tag type: 'reset', data: { target: friend.id } do %>
            <%= image_tag "close.png" %>
          <% end %>
        </div>
        <div class="delete-button">
          <%= link_to friend_path(friend),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <%= image_tag "trash-can.png" %>
                    <% end %>
        </div>
      </div>
  <% end %>

</div>

app/views/friends/_friend_form.html.erb
<div class="bg-div">
  <div class="main-div">
    <%= simple_form_for (@friend) do |f| %>
      <%= f.error_notification %>
      <div class="friend-form">
        <div class="inputs-div">
          <%= f.input :name, :label => false, :placeholder => "Name" %>
          <%= f.input :email, :label => false, :placeholder => "Email", input_html: { autocomplete: 'email' } %>
        </div>
    <%#= f.input :avatar, as: :file, input_html: { accept: User::AVATAR } %>
        <div class="submit-cancel-buttons adding-form">
          <%= button_tag type: 'submit' do %>
            <%= image_tag "accept.png" %>
          <% end %>
          <%= link_to friends_path do %>
            <%= image_tag "close.png" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/friends/_friend_index.html.erb
<div class="each-friends-container">
  <div class="friend-details" data-friend="<%= friend.id %>">
    <div class="friends-name">
      <p><%= friend.name.capitalize %> <br> <%= friend.email %></p>
    </div>
    <div  class="edit-button" data-target="<%= friend.id %>">
      <%= image_tag "pencil.png" %>
    </div>
  </div>
  <div id="<%= friend.id %>" class="friend-edit-form d-none">
    <%= render "friend_edit", friend: friend %>
  </div>
</div>

app/views/friends/edit.html.erb
<%= render 'shared/navbar' %>

<%= render "friend_edit" %>

app/views/friends/index.html.erb
<%= render 'shared/navbar' %>

<div class="body-friends">
<br>
<div class="add-new">
  <%= link_to  "+ Add Friend", new_friend_path %>
</div>

<div class="main-div">
  <div id="friends-div">
    <% @friends.each do |friend| %>
      <%= render "friend_index", friend: friend %>
    <% end %>
  </div>
</div>
</div>

app/views/friends/new.html.erb
<%= render 'shared/navbar' %>

<%= render "friend_form" %>

app/views/friends/show.html.erb
<%= render 'shared/navbar' %>

<h1><%= @friend.name %></h1>
<p> <%= @friend.email %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>softmind</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
    <%= favicon_link_tag asset_path('butterfly1.png') %>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/moments/_moment_form.html.erb
<div class="card-white">
  <h1>Hey <%= @friend.name %>!</h1><br>
  <%= simple_form_for @moment do |f| %>
    You’re about to upload encouraging content for your friend <%= User.find(@friend.user_id).first_name.capitalize %>. <br> You're a wonderful friend!<br><br>
    <p>Upload something of value to <%= User.find(@friend.user_id).first_name.capitalize %> — <br>a photo, video, audio, a few words etc.</p>
    <br>
    <i class="center fab fa-telegram-plane fa-5x"></i><br><br><br>
      <%= f.input :media, :multiple => true, input_html: { class: "white" }, label:"Add media:"%>
      <%= f.input :text_content, label: "Add a beautiful message here:" %>
      <%= f.input :user_id, as: :hidden, input_html: {value: @friend.user.id} %>
      <%= f.input :friend_id, as: :hidden, input_html: {value: @friend.id} %>
    <%= f.submit 'Publish', class: "btn" %>
  <% end %>
</div>

app/views/moments/carrousel.html.erb
<div id="play-container">
    <%= link_to moments_path do %>
        <i class="carrousel-exit fas fa-times"></i>
    <% end %>
        <% @moments.each do |moment| %>
            <% if @moment == moment %>
                <% @show_class = 'show-carrousel' %>
            <% else %>
                <% @show_class = 'unshow-carrousel' %>
            <% end %>
            <% if moment.media_type == "video" %>
                <div class="timeline-media play-moments-media <%= @show_class %>">
                        <%= video_tag(moment.media.url, :transformation=>
                {crop: "fit"}, controls: true, preload: 'true', :class => "moments-video moments-media") %>
                    <div class="text-box">
                        <p><%= moment.text_content %></p>
                    </div>
                </div>
            <% elsif moment.media_type == "image" %>
                <div class="timeline-media play-moments-media <%= @show_class %>">
                    <p><%= cl_image_tag(moment.media, :transformation=>
                {crop: "fit"}, :class => "moments-media") %></p>
                    <div class="text-box">
                        <p><%= moment.text_content %></p>
                    </div>
                </div>
            <% else %>
                <div class="timeline-media play-moments-media <%= @show_class %>">
                    <div class="card-product">
                        <div class="card-product-infos">
                            <p><%= moment.text_content %></p>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
</div>

app/views/moments/index.html.erb
<%= render 'shared/navbar' %>

<div class="body-index">
<div class="index-container">
    <div id="top-container">
        <h1 class="timeline-title">Carebox <i class="em em-gift_heart" aria-role="presentation" aria-label="HEART WITH RIBBON"></i></h1>
        <div class="search">
            <%= form_tag moments_path, method: :get, class: "simple-form" do %>
            <%= text_field_tag :query,
                params[:query],
                placeholder: "Try searching for 'Mom'",
                class: "here"
            %>
                <%= submit_tag "Search", class: "btn-flat" %>
            <% end %>
            </div>
            <div id="button-box">
                <button type="button" class="moment-button" id="all-button">All</button>
                <button type="button" class="moment-button" id="video-button">Videos</button>
                <button type="button" class="moment-button" id="image-button">Images</button>
                <button type="button" class="moment-button" id="text-button">Words</button>
            </div>
    </div>
    <div id="secondary-tabs" class="unshow">
        <div id="video-tab" class="unshow">
            <% @videos.each do |video| %>
                <div class="card-product">
                    <%= video_tag(video.media.url, controls: true, preload: 'true', :class => "tab-media") %>
                </div>
            <% end %>
        </div>
        <div id="image-tab" class="unshow">
            <% @images.each do |image| %>
                <div class="moment-card card-product-img-tab">
                    <%= link_to (cl_image_tag image.media, :class => "tab-media"), moment_carrousel_path(image) %>
                </div>
            <% end %>
        </div>
        <div id="text-tab" class="unshow">
            <% @texts.each do |text| %>
            <div class="card-product">
                <div class="card-product-infos">
                    <p><%= text.text_content %></p>
                </div>
            </div>
        <% end %>
        </div>
    </div>

    <div id="timeline-container-default">
        <% @moments.each do |moment| %>
            <% if moment.media_type == "image" %>
                <div class="card-product default-index">
                    <%= link_to (cl_image_tag moment.media, :transformation=>
                    {crop: "fit"}, :class => "media"), moment_carrousel_path(moment) %>
                    <div class="card-product-infos">
                        <h2><%= moment.text_content %></h2>
                    </div>
                </div>
            <% else moment.media_type == "video" %>
                <div class="card-product default-index">
                    <%= video_tag("#{moment.media.url}", controls: true, preload: 'true', :transformation=>
                    {crop: "fit"}, :class => "media") %>
                    <div class="card-product-infos">
                        <h2><%= moment.text_content %></h2>
                    </div>
                </div>
            <% end %>
        <% end %>
        </div>
    </div>
  </div>

app/views/moments/new.html.erb
<div class="container">

    <%= render "moment_form.html.erb" %>

</div>

app/views/moments/none.html.erb
<%= render 'shared/navbar' %>

It seems like you currently have no new moments.

But no worries, go check out that lovely timeline of yours!

app/views/moments/show.html.erb
<%= @moments %>

app/views/moments/success.html.erb
<div class="card text">
  <h1>Thank you <br><%= @friend.name %>! </h1><br><br>
    <i class="center1 fas fa-check-circle fa-5x"></i><br><br><br>
    <p><%= User.find(@friend.user_id).first_name.capitalize %> will be very thankful!<br>
          Do you want to upload more media?</p><br>
      <button class="btn"><%= link_to "Yes, let's go!", new_moment_url(@friend.authentication_token) %></button>
</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<div class="home-container">
  <div class="logo-placement">
    <h1>softmind</h1>
  </div>

  <% if @unseens %>
    <%= cl_video_tag("Butterfly_softmind_shzzvz.mp4", autoplay: 'autoplay', loop: 'true', preload: 'auto', muted: 'true', class: 'animation') %>
  <% end %>
    <div class="play-button">
        <button class="" id="white">
            <%= link_to 'Play', :controller => :pages, :action => :play %>
        </button>
    </div>
  </div>
</body>

app/views/pages/play.html.erb
<div id="play-container" class="play-bg-gradient">

    <%= form_for( 'moments_seen', remote: true, method: 'put', url: seen_path, html: {class: "form-seen"}, authenticity_token: true) do |f| %>
        <input type="hidden" name="moment_ids" value="" class="input-seen">
        <i class="play-exit-icon fas fa-times" id="seen-exit"></i>
    <% end %>

    <% @moments.each do |moment| %>
        <% if moment.media.present? %>

            <% if Moment::VIDEO_TYPES.include?(moment.media.file.format) %>
                <div class="play-moments-media unshow" data-id="<%= moment.id %>">
                        <%= video_tag("#{moment.media.url}", controls: true, preload: 'true', size: "16x16", :class => "moments-video moments-media") %>
                    <div class="text-box">
                        <p><%= moment.text_content %></p>
                    </div>
                </div>
            <% elsif Moment::IMG_TYPES.include?(moment.media.file.format) %>
                <div class="play-moments-media unshow" data-id="<%= moment.id %>">
                    <%= (cl_image_tag moment.media, :fetch_format=>:auto, :crop=>"mfit", :gravity=>"faces", :class => "moments-media") %></p>
                    <div class="text-box">
                        <p><%= moment.text_content %></p>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p><%= moment.text_content %></p>
        <% end %>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-lewagon navbar-lewagon-white">

  <%= link_to moments_path do %>
    <button type="button" class="small"><%= image_tag "carebox.png" %></button>
  <% end %>

  <%= link_to root_path do %>
    <button type="button" class="small"><%= image_tag "home.png" %></button>
  <% end %>

  <%= link_to profile_path do %>
    <button type="button" class="small"><%= image_tag "profile.png" %></button>
  <% end %>

</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>

<div class="body-users">
<div class="log-out">
  <button class="log-out-button">
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </button>
</div>

<div class="profile-infos">
  <div class="profile-avatar">
    <%= image_tag  "bunny_4.png", alt: 'nice avatar' %>
  </div>

  <div class="users-name">
    <h2>
      <%= current_user.first_name.capitalize %>
      <%= current_user.last_name.capitalize %>
    </h2>
  </div>
</div>

<div id="profile-menu">
  <ul>
    <li><%= link_to "Your Profile", edit_user_registration_path %></li>
    <li><%= link_to "Friends", friends_path %></li>
    <li><%= link_to "Become a PRO member", root_path %></li>
  </ul>
</div>
</div>